"""Added field in User model

Revision ID: 716889d207c1
Revises: 
Create Date: 2025-02-22 12:52:36.342339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716889d207c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test2')

    # ### end Alembic commands ###
