"""Remove field in User model

Revision ID: b2b9f0097300
Revises: d18670231874
Create Date: 2025-02-22 12:55:15.892821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b9f0097300'
down_revision = 'd18670231874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test3')
        batch_op.drop_column('test2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('test3', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
